version: '3.1'

services:
  ftp:
    image: 'delfer/alpine-ftp-server:latest'
    container_name: ftp_server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=myuser|1234567
      - ADDRESS=127.0.0.1
    network_mode: "host"
    volumes:
      - ./files/:/ftp/myuser/